-- SOMENTE LEITURA. Não altera tabelas, dados, sequences ou histórico.
SELECT USER FROM DUAL;
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_PRECISION, DATA_SCALE,
       DATA_LENGTH, CHAR_USED, CHAR_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN ('TB_USUARIO','TB_ANIMAL','TB_CONSULTA','TB_VACINA','TB_LOG_ERRO')
ORDER BY TABLE_NAME,COLUMN_ID;
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE,STATUS,R_CONSTRAINT_NAME,DELETE_RULE
FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TB_%' ORDER BY TABLE_NAME,CONSTRAINT_NAME;
SELECT TABLE_NAME,CONSTRAINT_NAME,COLUMN_NAME,POSITION FROM USER_CONS_COLUMNS
WHERE TABLE_NAME IN ('TB_USUARIO','TB_ANIMAL','TB_CONSULTA','TB_VACINA') ORDER BY TABLE_NAME,CONSTRAINT_NAME,POSITION;
SELECT SEQUENCE_NAME,INCREMENT_BY,LAST_NUMBER FROM USER_SEQUENCES ORDER BY SEQUENCE_NAME;
SELECT TRIGGER_NAME,TABLE_NAME,STATUS FROM USER_TRIGGERS ORDER BY TABLE_NAME;
SELECT TABLE_NAME FROM USER_TABLES WHERE LOWER(TABLE_NAME) LIKE '%history%';
-- Se existirem, inspecione as tabelas de histórico com o nome/capitalização retornados acima.
SELECT 'TB_USUARIO' TABELA,COUNT(*) TOTAL,MAX(ID_USUARIO) MAIOR_ID FROM TB_USUARIO
UNION ALL SELECT 'TB_ANIMAL',COUNT(*),MAX(ID_ANIMAL) FROM TB_ANIMAL
UNION ALL SELECT 'TB_CONSULTA',COUNT(*),MAX(ID_CONSULTA) FROM TB_CONSULTA
UNION ALL SELECT 'TB_VACINA',COUNT(*),MAX(ID_VACINA) FROM TB_VACINA;
SELECT LOWER(EMAIL) EMAIL_NORMALIZADO,COUNT(*) QUANTIDADE FROM TB_USUARIO GROUP BY LOWER(EMAIL) HAVING COUNT(*)>1;
SELECT ID_CONSULTA,HORA_CONSULTA FROM TB_CONSULTA
WHERE HORA_CONSULTA IS NOT NULL AND NOT REGEXP_LIKE(HORA_CONSULTA,'^([01][0-9]|2[0-3]):[0-5][0-9]$');
-- Não selecione/exponha as senhas existentes para diagnóstico.
