CREATE TABLE TB_LOG_ERRO (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_PROCEDURE VARCHAR2(100),
    NOME_USUARIO VARCHAR2(50),
    DATA_ERRO DATE,
    CODIGO_ERRO NUMBER,
    MENSAGEM_ERRO VARCHAR2(500)
);

--Usuarios
CREATE TABLE TB_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    SENHA VARCHAR2(18) NOT NULL,
    CPF NUMBER(11) UNIQUE NOT NULL,
    TELEFONE NUMBER(11)
);

--Animais/Pets
CREATE TABLE TB_ANIMAL (
    ID_ANIMAL NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    NOME_ANIMAL VARCHAR2(30) NOT NULL,
    ESPEC_ANIMAL VARCHAR2(10) CHECK (ESPEC_ANIMAL IN ('CAO', 'GATO', 'COELHO', 'OUTRO')) NOT NULL,
    RACA_ANIMAL VARCHAR2(35),
    IDADE_ANIMAL VARCHAR2(30), -- Mantido VARCHAR2 pois o app manda "2 anos"
    PORTE_ANIMAL VARCHAR2(10) CHECK (PORTE_ANIMAL IN ('PEQUENO', 'MEDIO', 'GRANDE')),
    PESO_ANIMAL NUMBER(5,2),
    CONSTRAINT FK_ANIMAL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

--Vacinas
CREATE TABLE TB_VACINA (
    ID_VACINA NUMBER PRIMARY KEY,
    ID_ANIMAL NUMBER NOT NULL,
    NOME_VACINA VARCHAR2(30) NOT NULL,
    DATA_VACINA DATE NOT NULL,
    PROX_DOSE DATE,
    LOC_VACINACAO VARCHAR2(100),
    CONSTRAINT FK_VACINA_ANIMAL FOREIGN KEY (ID_ANIMAL) REFERENCES TB_ANIMAL(ID_ANIMAL)
);

--Consultas
CREATE TABLE TB_CONSULTA (
    ID_CONSULTA NUMBER PRIMARY KEY,
    ID_ANIMAL NUMBER NOT NULL,
    TIPO_CONSULTA VARCHAR2(30) NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    HORA_CONSULTA VARCHAR2(5), 
    LOCAL_CONSULTA VARCHAR2(100),
    CONSTRAINT FK_CONSULTA_ANIMAL FOREIGN KEY (ID_ANIMAL) REFERENCES TB_ANIMAL(ID_ANIMAL)
);

------------------------------------------------------
